spring:
  application:
    name: "Testing Playground"
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        validator:
          apply_to_ddl: false
        jdbc:
          batch_size: 50
  profiles:
    active:
      - dev
  jackson:
    time-zone: UTC

server:
  port: 8081

info:
  app:
    name: ${spring.application.name}
    build:
      version: "@project.version@"
      timestamp: "@maven.build.timestamp@"

management:
  metrics:
    tags:
      application: ${spring.application.name}
      version: "@project.version@"
      timestamp: "@maven.build.timestamp@"
  info:
    git:
      enabled: true
      mode: FULL
  endpoint:
    integrationgraph:
      enabled: true
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
